import { describe, expect, it } from 'vitest';
import type { ChallengePayload, ReportPayload } from '../src/shared/contracts';
import { challengeId, issueChallenge, issueManage, issueReport, issueVideoTicket, readChallenge, readManage, readReport, readVideoTicket } from '../src/worker/capabilities/tokens';
import { assertShareableUrl } from '../src/shared/domain/share';

const secret='test-secret-that-is-longer-than-thirty-two-characters';
const challenge:ChallengePayload={v:1,kind:'challenge',video:{source:'bilibili',bvid:'BV1B7411m7LV',cid:123,page:1,title:'测试视频',description:'',cover:'',duration:60},initiator:'测试者',createdAt:100,expiresAt:200,nonce:'nonce',mode:'classic'};
describe('capability separation',()=>{
  it('rejects tampering and expiry',async()=>{const token=await issueChallenge(challenge,secret);await expect(readChallenge(token,secret,150)).resolves.toEqual(challenge);await expect(readChallenge(`${token}x`,secret,150)).rejects.toMatchObject({code:'INVALID_TOKEN'});await expect(readChallenge(token,secret,201)).rejects.toMatchObject({code:'TOKEN_EXPIRED'});});
  it('does not interchange public, manage and report capabilities',async()=>{const publicToken=await issueChallenge(challenge,secret);const manage=await issueManage(await challengeId(publicToken),secret);const reportPayload:ReportPayload={v:1,kind:'report',video:challenge.video,outcome:'failed',elapsedSeconds:12,issuedAt:150,expiresAt:190,nonce:'report'};const report=await issueReport(reportPayload,secret);await expect(readManage(publicToken,secret)).rejects.toMatchObject({code:'INVALID_MANAGE_TOKEN'});await expect(readChallenge(manage,secret,150)).rejects.toMatchObject({code:'INVALID_TOKEN'});await expect(readReport(report,secret,150)).resolves.toEqual(reportPayload);expect(publicToken).not.toContain('bm1.');});
  it('hard-rejects manage tokens from every QR/card renderer',async()=>{const publicToken=await issueChallenge(challenge,secret);const manage=await issueManage(await challengeId(publicToken),secret);expect(()=>assertShareableUrl(`https://example.com/manage#m=${manage}`)).toThrow(/管理链接/);expect(()=>assertShareableUrl(`https://example.com/c/${publicToken}`)).not.toThrow();});
  it('strips temporary CDN media before a video can become a public challenge',async()=>{const unsafe={...challenge.video,media:['https://cdn.example/signed.mp4?secret=temporary']} as typeof challenge.video;const ticket=await issueVideoTicket(unsafe,180,secret);const decoded=await readVideoTicket(ticket,secret,150);expect(decoded.video).not.toHaveProperty('media');const publicToken=await issueChallenge({...challenge,video:unsafe},secret);expect(publicToken).not.toContain('temporary');expect(await readChallenge(publicToken,secret,150)).not.toHaveProperty('video.media');});
});
